<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2020sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:param name="deliverychannel2" select="'samples/xml/deliverychannel.xml'"/>
	<xsl:param name="portfolio2" select="'samples/xml/portfolio.xml'"/>
	<xsl:param name="productbasics2" select="'samples/xml/productbasics.xml'"/>
	<xsl:template match="/">
		<xsl:variable name="var1_initial" select="."/>
		<Response>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">file:///C:/Users/AldoValdez/git/apex-api-impl-demo/specs/contracts/product-1.0/samples/xml/response.xsd</xsl:attribute>
			<xsl:for-each select="attributes">
				<xsl:variable name="var2_cur" select="."/>
				<attributes>
					<xsl:copy-of select="@node()"/>
					<xsl:copy-of select="node()"/>
				</attributes>
			</xsl:for-each>
			<xsl:for-each select="document($productbasics2)/productBasics">
				<xsl:variable name="var3_cur" select="."/>
				<productBasics>
					<xsl:copy-of select="@node()"/>
					<xsl:copy-of select="node()"/>
				</productBasics>
			</xsl:for-each>
			<xsl:for-each select="document($deliverychannel2)/deliveryChannel">
				<xsl:variable name="var4_cur" select="."/>
				<deliveryChannel>
					<xsl:copy-of select="@node()"/>
					<xsl:copy-of select="node()"/>
				</deliveryChannel>
			</xsl:for-each>
			<xsl:for-each select="document($portfolio2)/portfolio">
				<xsl:variable name="var5_cur" select="."/>
				<portfolio>
					<xsl:copy-of select="@node()"/>
					<xsl:copy-of select="node()"/>
				</portfolio>
			</xsl:for-each>
		</Response>
	</xsl:template>
</xsl:stylesheet>
