fis-api-spi-apex-demo:
  deployment:
    replicaCount: 1
    image:
      name: docker.fnis.com/epo/fis/api/spi-apex-demo
      tag: 
      pullPolicy: Always
    spiapexdemoConfig: 'fis-api-spi-apex-demo-config'
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  routes:
    default:
      subdomain: sdlocpapp.fisdev.local
